resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      products:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 4000ms
    instances:
      products:
        baseConfig: default

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9100
      client:
        registration:
          client-app:
            provider: spring
            client-id: gatewayt-app
            client-secret: 123456
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:9100/authorized
            scope:
              - openid
              - profile
            client-name: client-app
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9100
  cloud:
    gateway:
      routes:
        - id: msvc-oauth
          uri: lb://msvc-oauth
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=2
        - id: msvc-users
          uri: lb://msvc-users
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: msvc-products
          uri: lb://msvc-products
          predicates:
            - Path=/api/products/**
          # - Header=X-Request-Id, 12345
          # - Method=GET,POST
          # - Query=color, verde
          # - Cookie=color, azul
          filters:
            - name: CircuitBreaker
              args:
                name: products
                statusCode: 500,404
                fallbackUri: forward:/api/items/11
            - StripPrefix=2
            - name: SampleCookie
              args:
                name: "user"
                message: "This is a sample cookie"
                value: "Aurelio"
        - id: msvc-items
          uri: lb://msvc-items
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Request-Foo, Bar
            - AddResponseHeader=X-Response-Foo, Bar
            - AddRequestParameter=foo, bar
