spring:
  cloud:
    gateway:
      routes:
        - id: mvsc-products
          uri: lb://mvsc-products
          predicates:
          - Path=/api/products/**
          filters:
          - StripPrefix=2
        - id: msvc-items
          uri: lb://msvc-items
          predicates:
          - Path=/api/items/**
          filters:
          - StripPrefix=2
